version: "3"
services:
    es-data02:
        image: elasticsearch:7.1.0
        container_name: es-data02
        environment: # setting container env
            - ES_JAVA_OPTS=${ES_JVM_OPTS}   # set es bootstrap jvm args
        restart: always
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - ./es-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ${DATA_DIR}:/usr/share/elasticsearch/data:rw
            - ${LOGS_DIR}:/usr/share/elasticsearch/logs:rw
        network_mode: "host"
        ports:
            - 9202:9202
            - 9302:9302
